### ISSUE TITLE
ExecuteSQL issues

### ISSUE THREAD

**Issue by Rydgel** [meteogrid/bindings-gdal#3]
Hello, I'm trying to do some SQL requests against a shapefile, but I'm not sure how to do it.

``` haskell
main :: IO ()
main = do
    withGDAL $ runGDAL_ $ do
      ds <- OGR.openReadOnly "ne_10m_admin_0_countries.shp"
      let src = sourceLayer_ $ executeSQL DefaultDialect "SELECT * FROM fondo" Nothing ds
      (fs :: [Feature]) <- runOGR (src $$ CL.consume)
```

This throws me a compilation error:

```
    Couldn't match type ‘l0’ with ‘l’
      because type variable ‘l’ would escape its scope
    This (rigid, skolem) type variable is bound by
      a type expected by the context: OGR s l [Feature]
      at app/Main.hs:45:28-53
    Expected type: Source (OGR s l) Feature
      Actual type: OGRSource s l0 Feature
    Relevant bindings include
      src :: OGRSource s l0 Feature (bound at app/Main.hs:44:11)
    In the first argument of ‘($$)’, namely ‘src’
    In the first argument of ‘runOGR’, namely ‘(src $$ CL.consume)’
```

I'm probably doing something wrong.

**Comment by albertov** [comment]
Hi.

Strange, this compiles fine on my system with 7.10.3:

``` haskell
{-# LANGUAGE ScopedTypeVariables, OverloadedStrings #-}
import GDAL
import OGR
import qualified Data.Conduit.List as CL

main :: IO ()
main = do
    withGDAL $ runGDAL_ $ do
      ds <- OGR.openReadOnly "ne_10m_admin_0_countries.shp"
      let src = sourceLayer_ $ executeSQL DefaultDialect "SELECT * FROM fondo" Nothing ds
      (fs :: [Feature]) <- runOGR (src $$ CL.consume)
      liftIO (print fs)
```

What version of GHC are you using? 

Also, try inlining `src` inside `runOGR`, I suspect type inference is getting confused since there's an `l` phantom type variable to prevent layer pointers from exiting the `runOGR` region.

**Comment by Rydgel** [comment]
Wow that was actually the fault of `{-# LANGUAGE GADTs #-}`.
Removing it made it works.

**Comment by Rydgel** [comment]
Thank you @albertov.
Do you plan on releasing this lib on Hackage?

**Comment by albertov** [comment]
Eventually yes but i'd like to write some haddocks first and do some cleanup (like extracting the conduit functionality into another package, i've just created #4 for it)

**Comment by Rydgel** [comment]
Alright, for now I'll be using it for my project as a Git repo with Stack.
Thanks for you lib btw :)

**Comment by Rydgel** [comment]
@albertov I think there is a memory issue somewhere. Calling the above code twice in a row makes the second fail with a segmentation fault. Or should I close something myself?

Edit: seems like I can only call `withGDAL` once. Maybe gdal is not thread safe?

**Comment by albertov** [comment]
> seems like I can only call withGDAL once. Maybe gdal is not thread safe?

`withGDAL` should only be called once from the main thread since it it registers and deregisters the driver manager which is a process-wide singleton. It is not thread-safe, calling it from several threads will surely cause a segfault.

`runGDAL` is however thread-safe and can run `GDAL`actions concurrently in different threads (I use this pattern extensively). However, there are some caveats since [GDAL itself is mostly thread-safe](https://trac.osgeo.org/gdal/wiki/FAQMiscellaneous#IstheGDALlibrarythread-safe) but not completely. The bindings try make it hard to express unsafe behaviour using the public API (eg: using an existential phantom type to prevent sharing a dataset among threads/`GDAL`-actions) but it is not bullet-proof. For example, it wont prevent you from writing to geotiff dataset A from one thread and read from geotiff dataset B from another thread, which is not safe. (I work around this using the [API proxy](http://www.gdal.org/gdal_api_proxy.html) 

> Thanks for you lib btw :)

You're welcome :) Thanks for the feedback!

**Comment by Rydgel** [comment]
@albertov This is what I ended up doing. Works pretty well so far.
I'm actually doing a web service (just an API) that queries a shapefile.

One thing I'm wondering tho, is that for now it seems I have to call `OGR.openReadOnly` on each request. I wonder if there is an overhead for this? I tried to open it in the main thread only once, but because of the phantom types you mentioned I seem to be unable to get it out of `runGDAL`.
I'm not sure if this is a performance issue, since I don't know how Gdal works internally.

**Comment by albertov** [comment]
> One thing I'm wondering tho, is that for now it seems I have to call OGR.openReadOnly on each request. I wonder if there is an overhead for this? I tried to open it in the main thread only once, but because of the phantom types you mentioned I seem to be unable to get it out of runGDAL.
> I'm not sure if this is a performance issue, since I don't know how Gdal works internally.

Yes, there's probably a noticeable overhead for opening the datasource on every request. They could be cached in a resource pool which ensures exclusive access to them since they're not safe to share among concurrent threads. However, as you have seen, there's no easy way to store these pointers for subsequent requests since they can't escape the runGDAL region (by design, since out of this region they're already closed and deallocated).

Perhaps some `unsafe*` functions could be exported to obtain a raw pointer to datasets and un-register them from the cleanup machinery for this use-case.

**Comment by Rydgel** [comment]
I will for now close this issue. I will reopen one if I think that not being able to store the `OGR.openReadOnly` pointer is a performance issue in my case.
